#!/bin/bash

# If this is the first time, format hdfs
if [ ! -d "/phonelab-data/hdfs/name" ]
then
    echo "formatting HDFS"
    $HADOOP_PREFIX/bin/hdfs namenode -format
fi

echo "starting Hadoop Namenode"
$HADOOP_PREFIX/sbin/hadoop-daemon.sh start namenode

echo "starting sshd"
/usr/sbin/sshd

# Beanstalkd
beanstalkd -p 3006 &
# Aurora
aurora -c ${HOME}/aurora.toml &

# Phonelab-go
mkdir -p /var/log/phonelab
phonelab-go-server -b 3006 -p 3007 1>&2 2>>/var/log/phonelab/server.log &

/bin/bash
